# -----------------------------------------------------------------------------------
# PureC tools
# -----------------------------------------------------------------------------------

PCROOT := $(ROOTDIR)/purec
include $(PCROOT)/Makefile.pc

# -----------------------------------------------------------------------------------
# Options from project makefile
# -----------------------------------------------------------------------------------

ifeq ($(PRJ),)
    default = gcc
else
    default = pc
endif

ifeq ($(PRGFLAGS),)
    PRGFLAGS = -S
endif

ifeq ($(CPUFLAGS),)
    CPUFLAGS 	    = -m68000
endif

ifeq ($(OPTS),)
    OPTS 	        = -Os
endif

# -----------------------------------------------------------------------------------
# Tools
# -----------------------------------------------------------------------------------

GCDIR			:= $(ROOTDIR)/gcc
LIBDIR			:= $(ROOTDIR)/lib

GCC			    := m68k-atari-mintelf-gcc
GAS			    := m68k-atari-mintelf-gcc
GLD			    := m68k-atari-mintelf-gcc
GSTRIP          := m68k-atari-mintelf-strip -s
GFLAGS          := m68k-atari-mintelf-flags

GCC_OBJS		:= $(GCDIR)/lib/lgcc.o

GCC_LIBDIR      := $(GCDIR)/lib
GCC_INCDIR      := $(GCDIR)/inc
GCC_BINDIR      := $(GCDIR)/bin

LIBCMINI_DIR	:= $(GCDIR)
LIBCMINI_INC    := $(GCDIR)/include
LIBCMINI_LIB    := $(GCDIR)/lib
LIBCMINI_CRT	:= $(LIBCMINI_LIB)/crt0.o
LIBCMINI_SRC    := $(GCDIR)/src/libcmini



# -----------------------------------------------------------------------------------
# GCC compiler flags
# -----------------------------------------------------------------------------------

MAPFILE = $(BIN).map

INCLUDE = -I. -I$(ROOTDIR)/gcc -I$(ROOTDIR)/lib

SFLAGS = $(OPTS) $(INCLUDE) -Wa,--register-prefix-optional

CFLAGS = $(OPTS) $(DEFS) $(INCLUDE) -I$(LIBCMINI_INC) \
	-std=c99 -fomit-frame-pointer -fno-exceptions -ffast-math \
    -Wa,--register-prefix-optional \
	-Wall -Wno-multichar -Wno-unused -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function -Wno-format
	#

LFLAGS = -L$(LIBCMINI_LIB) -nodefaultlibs -nostdlib -nostartfiles -lgcc -lcmini -Wl,-Map,$(MAPFILE)

LINKOBJS = $(LIBCMINI_CRT) $(GCC_OBJS) $(OBJS)



# -----------------------------------------------------------------------------------
# Standard rules
# -----------------------------------------------------------------------------------

.PHONY: prj pc gcc gcc_common_clean

all: $(default)

install: all
ifneq ($(cross),y)
ifneq ($(INSTALL_BINS),)
ifneq ($(INSTALL_ROOT),)
	cp $(INSTALL_BINS) $(INSTALL_ROOT)/
endif
endif
endif


clean:
	rm -f $(BIN)
	rm -f $(OBJS)
	rm -f $(OBJS:.o=.d)
	rm -f $(OBJS:.o=.O)
ifneq ($(MAPFILE),)
	rm -f $(MAPFILE)
endif
ifneq ($(CLEAN),)
	rm -f $(CLEAN)
endif

common_clean:
	rm -f $(GCC_OBJS)


# -----------------------------------------------------------------------------------
# PureC rules
# -----------------------------------------------------------------------------------

pc: $(PRJ)
	$(PCMAKE)
	$(PFLAGS) $(PRGFLAGS) $(BIN)
	$(POST)


# -----------------------------------------------------------------------------------
# GCC rules
# -----------------------------------------------------------------------------------

gcc: $(current_makefile) $(LINKOBJS)
	$(GCC) $(CFLAGS) $(CPUFLAGS) $(LINKOBJS) $(LFLAGS) -o $(BIN)
	$(GSTRIP) $(BIN)
	$(GFLAGS) $(PRGFLAGS) $(BIN)
	$(POST)

%.o : %.S
	$(GCC) $(SFLAGS) $(CPUFLAGS) -c $< -o $@

%.o : %.c
	$(GCC) $(CFLAGS) $(CPUFLAGS) -c $< -o $@

