
NAME = rvtest

BIN = $(NAME).tos
PRJ = $(NAME).prj

INSTALL_ROOT = c:/auto
INSTALL_BINS = $(BIN)

OBJS = main.o m_speed.o m_sprite.o m_scroll.o
# xcb.o

ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
