
ifeq ($(cross),y)
    PCC         := m68k-atari-tos-pc-pcc
    PASM        := m68k-atari-tos-pc-pasm
    PLINK       := m68k-atari-tos-pc-plink
    PCMAKE      := pcmake
    PRGFLG      := m68k-atari-mint-flags
else
    PCC         := pcc.ttp
    PASM        := pasm.ttp
    PLINK       := plink.ttp
    PCMAKE      := pcmake.ttp
    PRGFLG      := flags.ttp
endif
