
ifeq ($(cross),)
    ifeq ($(OS),Windows_NT)
        UNAME = Windows
    else
        UNAME = $(shell uname -s)
    endif

    ifeq ($(UNAME),FreeMiNT)
        cross = n
    else
        cross = y
    endif
endif


ifeq ($(cross),y)
	PCC			:= $(PCROOT)/m68k-atari-tos-pc-pcc
	PASM		:= $(PCROOT)/m68k-atari-tos-pc-pasm
	PLINK		:= $(PCROOT)/m68k-atari-tos-pc-plink
	PFLAGS		:= m68k-atari-mint-flags
	PCMAKE		:= $(PCROOT)/pcmake
else
	PCC			:= $(PCROOT)/pcc.ttp
	PASM		:= $(PCROOT)/pasm.ttp
	PLINK		:= $(PCROOT)/plink.ttp
	PFLAGS		:= $(PCROOT)/flags.ttp
	PCMAKE		:= $(PCROOT)/pcmake.ttp
endif

