
NAME = emulator

BIN = $(NAME).prg
PRJ = $(NAME).prj

INSTALL_ROOT = c:/auto
INSTALL_BINS = $(BIN)

OBJS = main.o asm.o nv.o banksw.o vdi.o \
	cards/vga.o \
	cards/cirrus.o \
	cards/oak.o \
	cards/s3.o \
	cards/wdc.o

ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
