
NAME = emulator

BIN = $(NAME).prg
PRJ = $(NAME).prj

INSTALL_ROOT = c:/auto
INSTALL_BINS = $(BIN)

OBJS = main.o asm.o nv.o cards/vga.o
# xcb.o

ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
