
NAME = sb

BIN = $(NAME).rvs
PRJ = purec.prj

OBJS = 	../../driver.o \
		../../driverlm.o \
		main.o \
		blaster.o \
		wss.o \
		ess.o \
		opl3sa.o \
		#
		
ROOTDIR = ../../../..
include $(ROOTDIR)/Makefile.cmn
