
NAME = rvsnd

BIN = $(NAME).prg
PRJ = purec.prj

OBJS = 	sys.o \
		sysasm.o \
		driver.o \
		pubapi.o \
		midi.o \
		mixer.o \
		sndxbios.o \
		#
		
ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
