#
# Environment variable CC should be set to path to cc.ttp
#
# 	example.prg 	AES example using mrsrc_load().
#

OFILES= main.o init.o events.o wind.o menu.o dialog.o update.o resoursc.c
CFLAGS=

example.prg : $(OFILES)
	$(CC) $(OFILES) -o example.prg

