
NAME = dsptest

BIN = $(NAME).tos
PRJ = purec.prj

INSTALL_ROOT = c:/raven
INSTALL_BINS = $(BIN)

ROOTDIR = ../../..

OBJS = main.o asm.o \
		sram.p56 \
		#

include $(ROOTDIR)/Makefile.cmn
