
NAME = gus

BIN = $(NAME).rvs
PRJ = purec.prj

OBJS = 	../../driver.o \
		../../driverlm.o \
		main.o \
		init.o \
#		mixer.o \
		#
		
ROOTDIR = ../../../..
include $(ROOTDIR)/Makefile.cmn
