
NAME = dspxbios

BIN = $(NAME).tos
PRJ = purec.prj

INSTALL_ROOT = c:/raven
INSTALL_BINS = $(BIN)

ROOTDIR = ../../..
OBJS = main.o asm.o $(ROOTDIR)/dsp/boot.i56

include $(ROOTDIR)/Makefile.cmn
