./fabs.ttp 2> fabs.log
./facos.ttp 2> facos.log
./fadd.ttp 2> fadd.log
./fasin.ttp 2> fasin.log
./fatan.ttp 2> fatan.log
./fatanh.ttp 2> fatanh.log
./fcmp.ttp 2> fcmp.log
./fcos.ttp 2> fcos.log
./fcosh.ttp 2> fcosh.log
./fdiv.ttp 2> fdiv.log
./fetox.ttp 2> fetox.log
./fetoxm1.ttp 2> fetoxm1.log
./fgetexp.ttp 2> fgetexp.log
./fgetman.ttp 2> fgetman.log
./fint.ttp 2> fint.log
./fintrz.ttp 2> fintrz.log
./flog10.ttp 2> flog10.log
./flog2.ttp 2> flog2.log
./flogn.ttp 2> flogn.log
./flognp1.ttp 2> flognp1.log
./fmod.ttp 2> fmod.log
./fmul.ttp 2> fmul.log
./fneg.ttp 2> fneg.log
./frem.ttp 2> frem.log
./fscale.ttp 2> fscale.log
./fsin.ttp 2> fsin.log
./fsincos.ttp 2> fsincos.log
./fsinh.ttp 2> fsinh.log
./fsqrt.ttp 2> fsqrt.log
./fsub.ttp 2> fsub.log
./ftan.ttp 2> ftan.log
./ftanh.ttp 2> ftanh.log
./ftentox.ttp 2> ftentox.log
./ftwotox.ttp 2> ftwotox.log
