
NAME = dsprun

BIN = $(NAME).tos
PRJ = purec.prj

INSTALL_ROOT = c:/raven
INSTALL_BINS = $(BIN)

ROOTDIR = ../../..

OBJS =	main.o \
		buzz.p56 \
		thru.p56 \
		#

include $(ROOTDIR)/Makefile.cmn
