#define DOODMENU 0  	/* TREE */
#define DOODDESK 3  	/* OBJECT in TREE #0 */
#define DOODINFO 8  	/* OBJECT in TREE #0 */
#define DOODOPTS 5  	/* OBJECT in TREE #0 */
#define DOODPENS 24  	/* OBJECT in TREE #0 */
#define DOODERAP 23  	/* OBJECT in TREE #0 */
#define DOODINFD 1  	/* TREE */
#define DOODOK 6  	/* OBJECT in TREE #1 */
#define DOODPEND 3  	/* TREE */
#define DOODPSOK 10  	/* OBJECT in TREE #3 */
#define DOODCNCL 12  	/* OBJECT in TREE #3 */
#define DOODFILE 4  	/* OBJECT in TREE #0 */
#define DOODLOAD 17  	/* OBJECT in TREE #0 */
#define DOODSAVE 18  	/* OBJECT in TREE #0 */
#define DOODQUIT 19  	/* OBJECT in TREE #0 */
#define DOODOVWR 0  	/* STRING */
#define DOODNWDW 1  	/* STRING */
#define DOODSVAS 20  	/* OBJECT in TREE #0 */
#define DOODSVAD 2  	/* TREE */
#define DOODSOK 2  	/* OBJECT in TREE #2 */
#define DOODSCNL 3  	/* OBJECT in TREE #2 */
#define DOODNAME 4  	/* OBJECT in TREE #2 */
#define DOODABAN 21  	/* OBJECT in TREE #0 */
#define DOODIMG 9  	/* OBJECT in TREE #1 */
#define DOODPCLR 18  	/* OBJECT in TREE #3 */
#define DOODPFIN 3  	/* OBJECT in TREE #3 */
#define DOODPMED 4  	/* OBJECT in TREE #3 */
#define DOODPBRD 5  	/* OBJECT in TREE #3 */
#define DOODEFIN 6  	/* OBJECT in TREE #3 */
#define DOODEMED 7  	/* OBJECT in TREE #3 */
#define DOODEBRD 8  	/* OBJECT in TREE #3 */
