
NAME = eiffelcf

BIN = $(NAME).app
PRJ = $(NAME).prj

INSTALL_ROOT = c:/raven/eiffel
INSTALL_BINS = $(BIN) eiffel_g.rsc

OBJS = eiffelcf.o update.o

ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
