
NAME = rvnova

BIN = $(NAME).prg
PRJ = $(NAME).prj

INSTALL_ROOT = c:/auto
INSTALL_BINS = $(BIN)

OBJS = main.o rvnova.o lowlevel.o
# xcb.o

ROOTDIR = ..
include $(ROOTDIR)/Makefile.cmn
