#
# Environment variable CC should be set to path to cc.ttp
#
#	vcolor.prg		Fade to black
#	vcopy.prg		vro_cpyfm()
#	vcursor.prg		cursor movement
#	vdraw.prg		Various graphic drawing functions.
#	vex.prg			Vector exchanges
#	vfill.prg		Area fill functions.
#	vfont.prg		Display font info.
#	vkey.prg		Keyboard and Mouse states.
#	vpixel.prg		Mouse form change, get pixel value.
#	vtext.prg		Display text with different attributes.
#

vcolor.prg : vcolor.o grafstuf.o
	$(CC) vcolor.o grafstuf.o -o vcolor.prg

vcopy.prg : vcopy.o grafstuf.o
	$(CC) vcopy.o grafstuf.o -o vcopy.prg

vcursor.prg : vcursor.o grafstuf.o
	$(CC) vcursor.o grafstuf.o -o vcursor.prg

vdraw.prg : vdraw.o grafstuf.o
	$(CC) vdraw.o grafstuf.o -o vdraw.prg

vex.prg : vex.o grafstuf.o
	$(CC) vex.o grafstuf.o -o vex.prg

vfill.prg : vfill.o grafstuf.o
	$(CC) vfill.o grafstuf.o -o vfill.prg

vfont.prg : vfont.o grafstuf.o
	$(CC) vfont.o grafstuf.o -o vfont.prg

vkey.prg : vkey.o grafstuf.o
	$(CC) vkey.o grafstuf.o -o vkey.prg

vpixel.prg : vpixel.o grafstuf.o
	$(CC) vpixel.o grafstuf.o -o vpixel.prg

vtext.prg : vtext.o grafstuf.o
	$(CC) vtext.o grafstuf.o -o vtext.prg
