#
# Makefile for bell.prg
#

HDR =		..\h
SRC =		bell.c
CFLAGS =	-i$(HDR) -w -v -rr -cism -d2 -Oloop

bell.prg: $(SRC) $(HDR)\tsr.h
	$(CC) $(CFLAGS) -o$@ -t= $(SRC)
	@prgflags 7 1 $@

all: bell.prg

clean:
	-rm -f *.o *~* *.lnk

realclean: clean
	rm *.prg
