Pr„prozessorkommando fehlerhaft
unerwartetes Dateiende
Datei nicht gefunden $
lexikalisches Symbol nicht vorhanden
fehlerhafter Gebrauch eines Makros
šberlauf des Zeilenpuffers
Dateistapel voll
nicht erlaubte Umwandlung 
nicht definierter Bezeichner $
fehlerhafter Ausdruck als Feld-Index 
Zeichenkette zu lang oder nicht beendet
fehlerhafter Bezug auf Struktur 
Komponentenname fehlt
Komponente nicht definiert $
fehlerhafter Funktionsaufruf
fehlerhaftes Argument in Funktion
zu viele Operanden
Operator nicht aufl”sbar
runde Klammern nicht Ausgeglichen
fehlerhafter konstanter Ausdruck
unerlaubter Gebrauch von Aggregaten
Struktur als Argument in Funktion verwand
fehlerhafter Gebrauch eines abh„ngigen Operators
Operand mu Zeiger sein
ver„nderbarer "lvalue" ben”tigt
arithmetischer Operand ben”tigt
Operand mu arithmetisch oder Zeiger sein
fehlender Operand
fehlerhafte Operation mit Zeiger 
Zeiger weisen auf unterschiedliche Arten von Objekten
unvollst„ndiger Operand 
fehlerhafte Umwandlung angegeben
Vorbesetzung von AUTO-Objekten nicht erlaubt
Ausdruck zur Vorbesetzung fehlerhaft
schlieende geschweifte Klammer erwartet
Dieser Befehl kann im Programmablauf nicht erreicht werden
Marke fr Befehl doppelt vorhanden $
geschweifte Klammern nicht Ausgeglichen
fehlerhafter Gebrauch eines reservierten Wortes $
BREAK mu in einer Schleife oder in einem SWITCH-Block auftreten
CASE nicht in einem SWITCH-Block
fehlerhafter CASE-Ausdruck  
CASE Wert doppelt vorhanden
CONTINUE nicht in einer Schleife
DEFAULT nicht in einem SWITCH-Block
mehr als eine DEFAULT Anweisung
WHILE zur DO-Anweisung fehlt
fehlerhafter WHILE-Ausdruck
ELSE geh”rt zu keinem IF
Marke zu GOTO nicht vorhanden
Marke schon als Variable definiert $
Ausdruck zur IF-Anweisung nicht vorhanden 
RETURN-Ausdruck kann nicht konvertiert werden
SWITCH-Ausdruck fehlerhaft
SWITCH Befehl enth„lt keine CASE-Anweisung
Doppelpunkt erwartet
Strichpunkt erwartet
fehlende runde Klammer
ungltige Speicherklasse
unvereinbare Typen in Zuweisung oder Vergleich
undefiniertes STRUCT/UNION Kennwort $
E62
Deklaration des Ausdrucks doppelt vorhanden $
Struktur enth„lt keine Komponenten
fehlerhafte Definition einer Funktion
fehlerhafte Feldgrenzen
Objekt nicht erlaubt
Funktion innerhalb einer Struktur nicht erlaubt
Struktur enth„lt sich selbst
Funktion als formaler Parameter
Fehler in formaler Deklaration $
externes Objekt mit unterschiedlichen Eigenschaften
Deklaration erwartet
Daten zur Vorbesetzung nicht vollst„ndig bernommen
Anwendung von SIZEOF auf Bit-Feld
linke geschweifte Klammer erwartet
Bezeichner erwartet
Marke nicht definiert $
Wert in Aufz„hlungsliste doppelt vorhanden
Bitfeld fehlerhaft
Pr„prozessor: Schleife in Symbolauswertung 
Objekt zu gro oder zu wenig Speicher 
Bezug liegt auerhalb der Objektgrenzen
Neu-Definition des Pr„prozessor-Symbols $
Rckgabewert der Funktion stimmt nicht berein
Die formale Deklaration steht in Widerspruch zur Typenliste
Die Anzahl der Argumente stimmt nicht
Der Typ der Argumente stimmt nicht
Konstante in erforderlichen Typ umgewandelt
Der Bezeichner des Argumenttyps ist fehlerhaft
VOID-Operand ist hier nicht erlaubt
Statement hat keine Wirkung
kein Bezug auf Bezeichner $
AUTO-Variable nicht vorbesetzt $
#pragma Operand nicht erkannt
fehlender Name fr #pragma libcall/syscall/inline
E97
E98
Versuch einen konstanten "lvalue" zu ver„ndern
kein Prototyp fr Funktion deklariert
redundante Schlsselw”rter in der Deklaration
Widersprchliche Schlsselw”rter in der Deklaration
Konstante hat keinen Wert $
Umwandlung von Zeiger auf Konstante/volatile zu Zeiger auf Variable/volatile
E105 $
postfix Ausdrcke nicht anwendbar auf Konstanten
zu viele Vorbesetzungen
E108 $
fehlerhafter Gebrauch einer Typen-Bezeichnung oder eines Schlsselwortes
E110 $
E111 $
E112 $
E113 $
E114 $
E115 $
nicht definiertes Kennwort einer Aufz„hlung $
Aufz„hlung enth„lt keine Komponnenten
Sich ausschlieender Gebrauch des UNION/STRUCT/ENUM Kennwortes $
Bezeichner der Definition oder Funktion fehlt $
E120 $
hexadezimale Konstante zu gro fr CHAR (h”herwertige Bits gehen verloren)
fehlende Auslassung
Kein Kennwort fr Aufz„hlung definiert (kann keinen Prototyp erzeugen)
Symboltabelle fr den Debugger l„uft ber
ungltige Nummer
#ENDIF, #ELSE, or #ELIF ohne zugeh”riges #IF
Operand zu # Operator mu ein Makro-Argument sein
$
mehrdeutige Komponente $
E130
E131
Zus„tzliche Symbole nach gltiger Pr„prozessor-Anweisung
Kann das Makro nicht umdefinieren $
Zu viele Argumente
Zuweisung auf krzeren Datentyp (Verlust an Genauigkeit m”glich)
fehlerhafter Gebrauch eines REGISTER Schlsselwortes
E137
E138
Fehlendes #ENDIF
Anwendung des SIZEOF-Operators auf Feld, das in einen Zeiger umgewandelt wurde
E141
Feldgr”e niemals angegeben fr $
Objekt hat keine Adresse
Ben”tigter Speicher fr Strings und Konstanten berschreitet Maximum
E145
langer CASE-Wert in kurzem SWITCH
Umwandlung von Zeigern auf Funktionen/Daten in Zeiger auf Daten/Funktionen
Gebrauch unvollst„ndiger STRUCT/UNION/ENUM Kennworte $
E149 $
E150
Verwendung der flexiblen ANSI Schlsselwort-Anordnung
Funktion kann nicht mit TYPEDEF definiert werden
String-Konstanten k”nnen nicht verkettet werden
Kein Prototyp fr Funktionszeiger definiert
Kein Statement nach Marke
E156
E157
E158
E159
E160
no prototype at definition of function
E162
E163
E164
E165
unbalanced comment
nested comment detected
E168
E169
C++-style comment detected
implicit cast of integral argument
