
NAME = test

BIN = $(NAME).tos
PRJ = purec.prj

INSTALL_ROOT = c:/raven
INSTALL_BINS = $(BIN)

OBJS = main.o asm.o \
		test.p56 test3.p56 testram.p56 \
		../../dsp/boot.i56 \
		#

ROOTDIR = ../..
include $(ROOTDIR)/Makefile.cmn
