
NAME = isa_bios

BIN = $(NAME).prg
PRJ = $(NAME).prj

INSTALL_ROOT = c:/auto
INSTALL_BINS = $(BIN)

OBJS	= 	isa_bios.o \
			isa_core.o \
			isa_rw.o \
			isa_pnp.o \
			isa_probe.o

ROOTDIR	=	../..
include $(ROOTDIR)/Makefile.cmn
