#define PARMTEXT 1
#define PARMDLOG 2
#define PARMOK 2
#define MENUBAR 0
#define DESK 3
#define EDIT 5
#define FILE 4
#define ABOUT 8
#define FILENEW 17
#define FILEOPEN 19
#define FILECLOS 20
#define FILEQUIT 22
#define UNDO 24
#define CUT 26
#define COPY 27
#define PASTE 28
#define CLEAR 30
#define CANCEL 1
#define NAMEDLOG 1
#define OK 2
#define DLOGTEXT 5
