
all: clean
	make -C chip/opl
	make -C midi/mpu401
	make -C midi/opl
	make -C midi/raven
	make -C sound/sb

clean:
	make -C chip/opl clean
	make -C midi/mpu401 clean
	make -C midi/opl clean
	make -C midi/raven clean
	make -C sound/sb clean

